### ISSUE TITLE
Indexing records outside the rootline throws Exception 1294587218.

### ISSUE THREAD

**Issue by friggingee** [TYPO3-Solr/ext-solr#1291]
Assume, you have a page tree with a root page and a storage folder where the storage folder is outside of the root page.
The TypoScript configuration/setup is located on the rootpage.
If Solr is configured to index records outside of the rootpage, i.e. the setting `Enable/Disable record tracking outside siteroot` is enabled in the extension setup and the indexer configuration for the record type has an `additionalPageIds` value set to the `uid` of the storage folder, the index queue is being built correctly but the indexing action itself fails with the following exception:

```
1294587218: TYPO3\CMS\Core\Error\Http\ServiceUnavailableException: No TypoScript template found! in /var/www/html/vendor/typo3/cms/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php:2554
Stack trace:
#0 /var/www/html/public/typo3conf/ext/solr/Classes/Util.php(484): TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController->getConfigArray()
#1 /var/www/html/public/typo3conf/ext/solr/Classes/Util.php(340): ApacheSolrForTypo3\Solr\Util::initializeTsfe('316', 0)
#2 /var/www/html/public/typo3conf/ext/solr/Classes/Util.php(300): ApacheSolrForTypo3\Solr\Util::buildConfigurationArray('316', '', true, 0)
#3 /var/www/html/public/typo3conf/ext/solr/Classes/Util.php(251): ApacheSolrForTypo3\Solr\Util::getConfigurationFromPageId('316', '', true, 0)
#4 /var/www/html/public/typo3conf/ext/solr/Classes/IndexQueue/Indexer.php(275): ApacheSolrForTypo3\Solr\Util::getSolrConfigurationFromPageId('316', true, 0)
#5 /var/www/html/public/typo3conf/ext/solr/Classes/IndexQueue/Indexer.php(301): ApacheSolrForTypo3\Solr\IndexQueue\Indexer->getItemTypeConfiguration(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item), 0)
#6 /var/www/html/public/typo3conf/ext/solr/Classes/IndexQueue/Indexer.php(158): ApacheSolrForTypo3\Solr\IndexQueue\Indexer->itemToDocument(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item), 0)
#7 /var/www/html/public/typo3conf/ext/solr/Classes/IndexQueue/Indexer.php(130): ApacheSolrForTypo3\Solr\IndexQueue\Indexer->indexItem(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item), 0)
#8 /var/www/html/public/typo3conf/ext/solr/Classes/Domain/Index/IndexService.php(195): ApacheSolrForTypo3\Solr\IndexQueue\Indexer->index(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item))
#9 /var/www/html/public/typo3conf/ext/solr/Classes/Domain/Index/IndexService.php(129): ApacheSolrForTypo3\Solr\Domain\Index\IndexService->indexItem(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item), Object(ApacheSolrForTypo3\Solr\System\Configuration\TypoScriptConfiguration))
#10 /var/www/html/public/typo3conf/ext/solr/Classes/Backend/SolrModule/IndexQueueModuleController.php(227): ApacheSolrForTypo3\Solr\Domain\Index\IndexService->indexItems(10)
#11 [internal function]: ApacheSolrForTypo3\Solr\Backend\SolrModule\IndexQueueModuleController->doIndexingRunAction()
```

(In this case `316` is the `uid` of the storage folder.)

This regression seems to have been introduced betweeen version `6.0.1` and `6.1.0`.
Probably here: https://github.com/TYPO3-Solr/ext-solr/commit/c59f4f03022e30bc9e062fff6823aedac0f64c39#diff-99a1d1c23fd6b626eea8167b0dd97934

**Comment by timohund** [comment]
@friggingee Can you provide a testcase and a pull request?

**Comment by timohund** [comment]
@friggingee Is this pull request related: #1273 ?

**Comment by friggingee** [comment]
Definitely looks like it. I will be able to test this today and let you know if it solves the issue.

**Comment by timohund** [comment]
@friggingee I've used the patch from @hornschmalz as base and created a new pull request #1299. Can you please test, if this one resolves your problem? I'll backport it to release-6.1.x then as well.
