### ISSUE TITLE
solrfal: Error when updating some files in filelist…

### ISSUE THREAD

**Issue by alappe** [TYPO3-Solr/ext-solr#2011]
```
Fatal error: Uncaught TypeError: Argument 4 passed to ApacheSolrForTypo3\\Solrfal\\Queue\\RequeueItemHandler::postProcessIndexQueueUpdateItem() must be of the type integer, null given, called in /web/typo3conf/ext/solr/Classes/IndexQueue/Queue.php on line 292 and defined in /web/typo3conf/ext/solrfal/Classes/Queue/RequeueItemHandler.php:59
Stack trace:
#0 /web/typo3conf/ext/solr/Classes/IndexQueue/Queue.php(292): ApacheSolrForTypo3\\Solrfal\\Queue\\RequeueItemHandler->postProcessIndexQueueUpdateItem('pages', 5668, 0, NULL)
#1 /web/typo3conf/ext/solr/Classes/IndexQueue/Queue.php(229): ApacheSolrForTypo3\\Solr\\IndexQueue\\Queue->postProcessIndexQueueUpdateItem('pages', 5668, 0, NULL)
#2 /web/typo3conf/ext/solrfal/Classes/Detection/PageContextDetector.php(360): ApacheSolrForTypo3\\Solr\\IndexQueue\\Queue->updateItem('pages', 5668, NULL, 1529048270)
#3 /…  ', referer: https://xxxxxxxxx/typo3/index.php?M=file_FilelistList&moduleToken=…
```

PHP Version: `7.0.30`
TYPO3 Version: `8.7.13`

**Comment by timohund** [comment]
This is not the issue tracker for solrfal. Please send solrfal bug reports to solr-eb-support@dkd.de. For this issue we allready have a patch, if you want i can send you the current master state and it would be nice when you could give me feedback if this resolves you problem.

**Comment by alappe** [comment]
![](https://media2.giphy.com/media/tGZRCBAPhCXxm/giphy.gif)
