### ISSUE TITLE
[BUG] Wrong indexing URL if the base URL contains a port

### ISSUE THREAD

**Issue by stat1x** [TYPO3-Solr/ext-solr#2524]
If the base URL contains a port (i. e. https://test.ddev.site:4443/), when trying to index page content in the backend module the indexing URL is wrong. It looks like this : `https://test.ddev.site4443` but it should be `https://test.ddev.site:4443`.

Here is the stack trace :

```
0: GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: test.ddev.site4443 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) in /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:200
Stack trace:
#0 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(155): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(105): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /var/www/html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(37): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(29): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /var/www/html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(59): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /var/www/html/vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\Client->requestAsync('GET', Object(GuzzleHttp\Psr7\Uri), Array)
#13 /var/www/html/vh_typo3/typo3/sysext/core/Classes/Http/RequestFactory.php(39): GuzzleHttp\Client->request('GET', 'https://test...', Array)
#14 /var/www/html/vh_typo3/typo3conf/ext/solr/Classes/IndexQueue/PageIndexerRequest.php(411): TYPO3\CMS\Core\Http\RequestFactory->request('https://test...', 'GET', Array)
#15 /var/www/html/vh_typo3/typo3conf/ext/solr/Classes/IndexQueue/PageIndexerRequest.php(202): ApacheSolrForTypo3\Solr\IndexQueue\PageIndexerRequest->getUrl('https://test...', Array, 60)
#16 /var/www/html/vh_typo3/typo3conf/ext/solr/Classes/IndexQueue/PageIndexerRequest.php(169): ApacheSolrForTypo3\Solr\IndexQueue\PageIndexerRequest->getUrlAndDecodeResponse('https://test...', Object(ApacheSolrForTypo3\Solr\IndexQueue\PageIndexerResponse))
#17 /var/www/html/vh_typo3/typo3conf/ext/solr/Classes/IndexQueue/PageIndexer.php(163): ApacheSolrForTypo3\Solr\IndexQueue\PageIndexerRequest->send('https://test...')
#18 /var/www/html/vh_typo3/typo3conf/ext/solr/Classes/IndexQueue/PageIndexer.php(62): ApacheSolrForTypo3\Solr\IndexQueue\PageIndexer->getAccessGroupsFromContent(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item), 0)
#19 /var/www/html/vh_typo3/typo3conf/ext/solr/Classes/Domain/Index/IndexService.php(206): ApacheSolrForTypo3\Solr\IndexQueue\PageIndexer->index(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item))
#20 /var/www/html/vh_typo3/typo3conf/ext/solr/Classes/Domain/Index/IndexService.php(132): ApacheSolrForTypo3\Solr\Domain\Index\IndexService->indexItem(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item), Object(ApacheSolrForTypo3\Solr\System\Configuration\TypoScriptConfiguration))
#21 /var/www/html/vh_typo3/typo3conf/ext/solr/Classes/Controller/Backend/Search/IndexQueueModuleController.php(259): ApacheSolrForTypo3\Solr\Domain\Index\IndexService->indexItems(10)
#22 /var/www/html/vh_typo3/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(318): ApacheSolrForTypo3\Solr\Controller\Backend\Search\IndexQueueModuleController->doIndexingRunAction()
```

**Used versions (please complete the following information):**
 - TYPO3 Version: 9.5.13
 - EXT:solr Version: 9.0.2
 - Used Apache Solr Version: typo3solr/ext-solr:9.0.0
 - PHP Version: 7.3

**Comment by stat1x** [comment]
I see it has been fixed here : https://github.com/TYPO3-Solr/ext-solr/commit/395d74c272871759bd32c45e7fabdc21579a99d7#diff-243d376d1e67c5f8eb977dc2aae1e279.
