### ISSUE TITLE
[TASK] Move all class properties from tests to getter methods

### ISSUE THREAD

**Issue by dkd-kaehm** [TYPO3-Solr/ext-solr#2615]
The test cases MUST be isolated from each other. The properties MUST NOT contain any state from previous test cases. Although the initialization of properties is done within the `setup()` method and they do not contain any state from previous test cases, they make troubles in phpunit, because php unit tries sometimes to serialize the test object and fails on defined properties. We have already multiple `__sleep()` methods to unset those properties. The `__sleep()` methods MUST be removed as well, after moving the properties to getter methods.

There are multiple class properties initialized on `setup()` methods. Like:

https://github.com/TYPO3-Solr/ext-solr/blob/d2efa3fb5be0b343cac995d411810ea4c8be8842/Tests/Integration/Controller/Backend/Search/IndexAdministrationModuleControllerTest.php#L42-L63

---

A test case could be implemented, which disallows defining properties within the test class. This should check the defined properties and fail if some is defined.

**Comment by dkd-kaehm** [comment]
On TYPO3 12 compatibility current state there are multiple errors like:

```log
ApacheSolrForTypo3\Solr\Tests\Integration\Controller\Backend\Search\IndexAdministrationModuleControllerTest::testReloadIndexConfigurationAction
PHPUnit\Framework\Exception: Fatal error: Uncaught Exception: Serialization of 'Closure' is not allowed in Standard input code:274
Stack trace:
#0 Standard input code(274): serialize(Array)
#1 Standard input code(515): __phpunit_run_isolated_test()
#2 {main}
  thrown in Standard input code on line 274

Caused by
ErrorException: unserialize(): Error at offset 0 of 275 bytes in /RAMFS_TESTS/ext-solr/.Build/vendor/phpunit/phpunit/src/Util/PHP/AbstractPhpProcess.php:289
Stack trace:
#0 [internal function]: PHPUnit\Util\PHP\AbstractPhpProcess::PHPUnit\Util\PHP\{closure}(8, 'unserialize(): ...', '/RAMFS_TESTS/ex...', 289)
#1 /RAMFS_TESTS/ext-solr/.Build/vendor/phpunit/phpunit/src/Util/PHP/AbstractPhpProcess.php(289): unserialize('\nFatal error: U...')
#2 /RAMFS_TESTS/ext-solr/.Build/vendor/phpunit/phpunit/src/Util/PHP/AbstractPhpProcess.php(183): PHPUnit\Util\PHP\AbstractPhpProcess->processChildResult(Object(ApacheSolrForTypo3\Solr\Tests\Integration\Controller\Backend\Search\IndexAdministrationModuleControllerTest), Object(PHPUnit\Framework\TestResult), '\nFatal error: U...', '')
#3 /RAMFS_TESTS/ext-solr/.Build/vendor/phpunit/phpunit/src/Framework/TestCase.php(962): PHPUnit\Util\PHP\AbstractPhpProcess->runTestJob('<?php\nuse PHPUn...', Object(ApacheSolrForTypo3\Solr\Tests\Integration\Controller\Backend\Search\IndexAdministrationModuleControllerTest), Object(PHPUnit\Framework\TestResult))
#4 /RAMFS_TESTS/ext-solr/.Build/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#5 /RAMFS_TESTS/ext-solr/.Build/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#6 /RAMFS_TESTS/ext-solr/.Build/vendor/phpunit/phpunit/src/Framework/TestSuite.php(684): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#7 /RAMFS_TESTS/ext-solr/.Build/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(651): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#8 /RAMFS_TESTS/ext-solr/.Build/vendor/phpunit/phpunit/src/TextUI/Command.php(144): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#9 /RAMFS_TESTS/ext-solr/.Build/vendor/phpunit/phpunit/src/TextUI/Command.php(97): PHPUnit\TextUI\Command->run(Array, true)
#10 /RAMFS_TESTS/ext-solr/.Build/vendor/phpunit/phpunit/phpunit(107): PHPUnit\TextUI\Command::main()
#11 /RAMFS_TESTS/ext-solr/.Build/bin/phpunit(123): include('/RAMFS_TESTS/ex...')
#12 {main}

```
