### ISSUE TITLE
[BUG] Site configuration env placeholders not always replaced

### ISSUE THREAD

**Issue by stigfaerch** [TYPO3-Solr/ext-solr#2952]
**Describe the bug**
Sometimes it happens that the env() placeholder isn’t replaced by the environment variable, defined like this:
solr_core_read: '%env(INSTANCE_NAME)%_dk'

This results in errors when trying to delete a content element (or a page with content elements):
```
Solr HTTP error: HTTP request failed, Client error: `POST http://ip-address-removed:49154/solr/%25env(INSTANCE_NAME)%25_dk/update?omitHeader=false&wt=json&json.nl=flat` resulted in a `404 Not Found` response: <html> <head> <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/> <title>Error 404 Not Found</title> </h (truncated...)
```

Also in the backend module, the drop down displays ‘/solr/%env(INSTANCE_NAME)%_dk’ instead of the expected core name.

**To Reproduce**
Currently seems randomly and have not yet found a way to reproduce.
When all cache is cleared, usually things works as expected again.
I guess the wrong value i stored here: /var/cache/code/cache_core/site-configuration.php

**Expected behavior**
Site configuration env placeholders should always be replaced

**Used versions (please complete the following information):**
 - TYPO3 Version: 9.5.23
 - EXT:solr Version: 11.0.2
 - Used Apache Solr Version: 8.5.2
 - PHP Version: 7.3
 - MySQL Version: 5.7

**Additional context**
Error log:
````
Thu, 27 May 2021 14:15:05 +0200 [CRITICAL] request="fd035d416ad9c" component="TYPO3.CMS.Core.Error.ProductionExceptionHandler": Core: Exception handler (WEB): Uncaught TYPO3 Excepti
on: Solr HTTP error: HTTP request failed, Client error: `POST http://{IP-ADDRESS-REMOVED}:49154/solr/%25env(INSTANCE_NAME)%25_dk/update?omitHeader=false&wt=json&json.nl=flat` resulted in a `404 Not Found` response:
 | Solarium\Exception\HttpException thrown in file /var/www/vhosts/example.com/httpdocs/vendor/solarium/solarium/src/Core/Client/Adapter/Guzzle.php in line 79. Requested URL: https://www.de4kirker.dk/typo3/index.php?route=%2Fajax%2Frecord%2Fprocess&token=--AnonymizedToken--&cmd[pages][2669][delete]=1 - {"TYPO3_MODE":"BE","exception":"Solarium\\Exception\\HttpException: Solr HTTP error: HTTP request failed, Client error: `POST http://172.20.168.4:49154/solr/%25env(DKM_3S_INSTANCE_NAME)%25_dk/update?omitHeader=false&wt=json&json.nl=flat` resulted in a `404 Not Found` response:
<html>
<head>
<meta http-equiv=\"Content-Type\" content=\"text/html;charset=utf-8\"/>
<title>Error 404 Not Found</title>
</h (truncated...)
 in /var/www/vhosts/example.com/httpdocs/vendor/solarium/solarium/src/Core/Client/Adapter/Guzzle.php:79
Stack trace:
#0 /var/www/vhosts/example.com/httpdocs/vendor/solarium/solarium/src/Core/Client/Client.php(813): Solarium\\Core\\Client\\Adapter\\Guzzle->execute(Object(Solarium\\Core\\Client\\Request), Object(Solarium\\Core\\Client\\Endpoint))
#1 /var/www/vhosts/example.com/httpdocs/public/typo3conf/ext/solr/Classes/System/Solr/Service/AbstractSolrService.php(343): Solarium\\Core\\Client\\Client->executeRequest(Object(Solarium\\Core\\Client\\Request))
#2 /var/www/vhosts/example.com/httpdocs/public/typo3conf/ext/solr/Classes/System/Solr/Service/AbstractSolrService.php(334): ApacheSolrForTypo3\\Solr\\System\\Solr\\Service\\AbstractSolrService->executeRequest(Object(Solarium\\Core\\Client\\Request))
#3 /var/www/vhosts/example.com/httpdocs/public/typo3conf/ext/solr/Classes/System/Solr/Service/SolrWriteService.php(94): ApacheSolrForTypo3\\Solr\\System\\Solr\\Service\\AbstractSolrService->createAndExecuteRequest(Object(Solarium\\QueryType\\Update\\Query\\Query))
#4 /var/www/vhosts/example.com/httpdocs/public/typo3conf/ext/solr/Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php(141): ApacheSolrForTypo3\\Solr\\System\\Solr\\Service\\SolrWriteService->deleteByQuery('type:pages AND ...')
#5 /var/www/vhosts/example.com/httpdocs/public/typo3conf/ext/solr/Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php(125): ApacheSolrForTypo3\\Solr\\Domain\\Index\\Queue\\GarbageRemover\\AbstractStrategy->deleteRecordInAllSolrConnections('pages', 2669, Array, '059785a6bd47054...', true)
#6 /var/www/vhosts/example.com/httpdocs/public/typo3conf/ext/solr/Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php(93): ApacheSolrForTypo3\\Solr\\Domain\\Index\\Queue\\GarbageRemover\\AbstractStrategy->deleteIndexDocuments('pages', 2669)
#7 /var/www/vhosts/example.com/httpdocs/public/typo3conf/ext/solr/Classes/Domain/Index/Queue/GarbageRemover/PageStrategy.php(76): ApacheSolrForTypo3\\Solr\\Domain\\Index\\Queue\\GarbageRemover\\AbstractStrategy->deleteInSolrAndRemoveFromIndexQueue('pages', 2669)
#8 /var/www/vhosts/example.com/httpdocs/public/typo3conf/ext/solr/Classes/Domain/Index/Queue/GarbageRemover/PageStrategy.php(49): ApacheSolrForTypo3\\Solr\\Domain\\Index\\Queue\\GarbageRemover\\PageStrategy->collectPageGarbageByPageChange(2669)
#9 /var/www/vhosts/example.com/httpdocs/public/typo3conf/ext/solr/Classes/Domain/Index/Queue/GarbageRemover/AbstractStrategy.php(71): ApacheSolrForTypo3\\Solr\\Domain\\Index\\Queue\\GarbageRemover\\PageStrategy->removeGarbageOfByStrategy('pages', 2669)
#10 /var/www/vhosts/example.com/httpdocs/public/typo3conf/ext/solr/Classes/GarbageCollector.php(121): ApacheSolrForTypo3\\Solr\\Domain\\Index\\Queue\\GarbageRemover\\AbstractStrategy->removeGarbageOf('pages', 2669)
#11 /var/www/vhosts/example.com/httpdocs/public/typo3conf/ext/solr/Classes/GarbageCollector.php(80): ApacheSolrForTypo3\\Solr\\GarbageCollector->collectGarbage('pages', 2669)
#12 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/core/Classes/DataHandling/DataHandler.php(3530): ApacheSolrForTypo3\\Solr\\GarbageCollector->processCmdmap_preProcess('delete', 'pages', 2669, '1', Object(TYPO3\\CMS\\Core\\DataHandling\\DataHandler), false)
#13 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/backend/Classes/Controller/SimpleDataHandlerController.php(296): TYPO3\\CMS\\Core\\DataHandling\\DataHandler->process_cmdmap()
#14 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/backend/Classes/Controller/SimpleDataHandlerController.php(160): TYPO3\\CMS\\Backend\\Controller\\SimpleDataHandlerController->processRequest()
#15 [internal function]: TYPO3\\CMS\\Backend\\Controller\\SimpleDataHandlerController->processAjaxRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#16 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/backend/Classes/Http/RouteDispatcher.php(93): call_user_func_array(Array, Array)
#17 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/backend/Classes/Http/RequestHandler.php(73): TYPO3\\CMS\\Backend\\Http\\RouteDispatcher->dispatch(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(TYPO3\\CMS\\Core\\Http\\Response))
#18 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/backend/Classes/Middleware/SiteResolver.php(59): TYPO3\\CMS\\Backend\\Http\\RequestHandler->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#19 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Backend\\Middleware\\SiteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(TYPO3\\CMS\\Backend\\Http\\RequestHandler))
#20 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/backend/Classes/Middleware/AdditionalResponseHeaders.php(39): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#21 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Backend\\Middleware\\AdditionalResponseHeaders->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#22 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/backend/Classes/Middleware/OutputCompression.php(45): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#23 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Backend\\Middleware\\OutputCompression->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#24 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/backend/Classes/Middleware/LegacyBackendTemplateInitialization.php(42): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#25 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Backend\\Middleware\\LegacyBackendTemplateInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#26 /var/www/vhosts/example.com/httpdocs/public/typo3conf/ext/tcamanipulate/Classes/Middleware/TCAManipulation.php(53): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#27 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): DKM\\TCAManipulate\\Middleware\\TCAManipulation->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#28 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/backend/Classes/Middleware/BackendUserAuthenticator.php(70): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#29 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Backend\\Middleware\\BackendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#30 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/backend/Classes/Middleware/BackendRouteInitialization.php(73): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#31 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Backend\\Middleware\\BackendRouteInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#32 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/backend/Classes/Middleware/ForcedHttpsBackendRedirector.php(53): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#33 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Backend\\Middleware\\ForcedHttpsBackendRedirector->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#34 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/backend/Classes/Middleware/LockedBackendGuard.php(71): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#35 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Backend\\Middleware\\LockedBackendGuard->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#36 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php(58): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#37 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(138): TYPO3\\CMS\\Core\\Middleware\
ormalizedParamsAttribute->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(class@anonymous))
#38 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(67): class@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#39 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(108): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#40 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/backend/Classes/Http/Application.php(68): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#41 /var/www/vhosts/example.com/httpdocs/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(120): TYPO3\\CMS\\Backend\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))
#42 /var/www/vhosts/example.com/httpdocs/public/typo3/index.php(24): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()
#43 /var/www/vhosts/example.com/httpdocs/public/typo3/index.php(25): {closure}()
#44 {main}"}
````

**Comment by stigfaerch** [comment]
@dmitryd maybe you have something that you would like to add?

**Comment by stigfaerch** [comment]
I still experience this.

**Comment by stigfaerch** [comment]
Ok. So I found that this has probably nothing to do with Solr. It's probably because that the environment variables are not always present (when CLI maybe). So I'm closing this issue for now.
