### ISSUE TITLE
[BUG] Drag & drop of a new page from the tree toolbar results in an error in ext-solr

### ISSUE THREAD

**Issue by YetiCGN** [TYPO3-Solr/ext-solr#2991]
**Describe the bug**
When drag-and-dropping a new page from the tree toolbar in the TYPO3 backend, an error occurs during the creation of the new page.

The error message reads: `PHP Warning: array_diff_assoc(): Expected parameter 2 to be an array, null given in /var/www/releases/20210812135306/public/typo3conf/ext/solr/Classes/AbstractDataHandlerListener.php line 175`

**To Reproduce**
1. Go to TYPO3 backend
2. Drag a new standard page (blank page icon) onto the page tree
3. Enter any title for the page and press Enter

**Expected behavior**
The new page should be saved without the error and queued for indexing in Solr.

**Screenshots**
Here's the stacktrace:

```
#0 /var/www/releases/20210812135306/public/typo3conf/ext/solr/Classes/AbstractDataHandlerListener.php(152): ApacheSolrForTypo3\Solr\AbstractDataHandlerListener->getAllCurrentStateFieldsMatch(Array, NULL)
#1 /var/www/releases/20210812135306/public/typo3conf/ext/solr/Classes/AbstractDataHandlerListener.php(121): ApacheSolrForTypo3\Solr\AbstractDataHandlerListener->isRecursiveUpdateRequired(NULL, Array)
#2 /var/www/releases/20210812135306/public/typo3conf/ext/solr/Classes/IndexQueue/RecordMonitor.php(391): ApacheSolrForTypo3\Solr\AbstractDataHandlerListener->isRecursivePageUpdateRequired(NULL, Array)
#3 /var/www/releases/20210812135306/public/typo3conf/ext/solr/Classes/IndexQueue/RecordMonitor.php(328): ApacheSolrForTypo3\Solr\IndexQueue\RecordMonitor->processRecord('pages', 9, NULL, Array)
#4 /var/www/releases/20210812135306/public/typo3/sysext/core/Classes/DataHandling/DataHandler.php(855): ApacheSolrForTypo3\Solr\IndexQueue\RecordMonitor->processDatamap_afterDatabaseOperations('new', 'pages', 'NEW_1', Array, Object(TYPO3\CMS\Core\DataHandling\DataHandler))
#5 /var/www/releases/20210812135306/public/typo3/sysext/core/Classes/DataHandling/DataHandler.php(1239): TYPO3\CMS\Core\DataHandling\DataHandler->hook_processDatamap_afterDatabaseOperations(Array, 'new', 'pages', 'NEW_1', Array)
#6 /var/www/releases/20210812135306/public/typo3/sysext/backend/Classes/Controller/SimpleDataHandlerController.php(242): TYPO3\CMS\Core\DataHandling\DataHandler->process_datamap()
#7 /var/www/releases/20210812135306/public/typo3/sysext/backend/Classes/Controller/SimpleDataHandlerController.php(137): TYPO3\CMS\Backend\Controller\SimpleDataHandlerController->processRequest()
#8 [internal function]: TYPO3\CMS\Backend\Controller\SimpleDataHandlerController->processAjaxRequest(Object(TYPO3\CMS\Core\Http\ServerRequest))
#9 /var/www/releases/20210812135306/public/typo3/sysext/backend/Classes/Http/RouteDispatcher.php(66): call_user_func_array(Array, Array)
#10 /var/www/releases/20210812135306/public/typo3/sysext/backend/Classes/Http/RequestHandler.php(94): TYPO3\CMS\Backend\Http\RouteDispatcher->dispatch(Object(TYPO3\CMS\Core\Http\ServerRequest))
#11 /var/www/releases/20210812135306/public/typo3/sysext/extbase/Classes/Middleware/SignalSlotDeprecator.php(49): TYPO3\CMS\Backend\Http\RequestHandler->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#12 /var/www/releases/20210812135306/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\CMS\Extbase\Middleware\SignalSlotDeprecator->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(TYPO3\CMS\Backend\Http\RequestHandler))
#13 /var/www/releases/20210812135306/public/typo3/sysext/backend/Classes/Middleware/SiteResolver.php(69): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#14 /var/www/releases/20210812135306/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\CMS\Backend\Middleware\SiteResolver->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#15 /var/www/releases/20210812135306/public/typo3/sysext/backend/Classes/Middleware/AdditionalResponseHeaders.php(41): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#16 /var/www/releases/20210812135306/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\CMS\Backend\Middleware\AdditionalResponseHeaders->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#17 /var/www/releases/20210812135306/public/typo3/sysext/backend/Classes/Middleware/OutputCompression.php(47): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#18 /var/www/releases/20210812135306/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\CMS\Backend\Middleware\OutputCompression->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#19 /var/www/releases/20210812135306/public/typo3/sysext/backend/Classes/Middleware/BackendUserAuthenticator.php(79): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#20 /var/www/releases/20210812135306/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\CMS\Backend\Middleware\BackendUserAuthenticator->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#21 /var/www/releases/20210812135306/public/typo3/sysext/backend/Classes/Middleware/BackendRouteInitialization.php(58): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#22 /var/www/releases/20210812135306/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\CMS\Backend\Middleware\BackendRouteInitialization->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#23 /var/www/releases/20210812135306/public/typo3/sysext/backend/Classes/Middleware/ForcedHttpsBackendRedirector.php(55): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#24 /var/www/releases/20210812135306/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\CMS\Backend\Middleware\ForcedHttpsBackendRedirector->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#25 /var/www/releases/20210812135306/public/typo3/sysext/backend/Classes/Middleware/LockedBackendGuard.php(75): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#26 /var/www/releases/20210812135306/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\CMS\Backend\Middleware\LockedBackendGuard->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#27 /var/www/releases/20210812135306/public/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php(45): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#28 /var/www/releases/20210812135306/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\CMS\Core\Middleware\NormalizedParamsAttribute->process(Object(TYPO3\CMS\Core\Http\ServerRequest), Object(class@anonymous))
#29 /var/www/releases/20210812135306/public/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(78): class@anonymous->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#30 /var/www/releases/20210812135306/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(85): TYPO3\CMS\Core\Http\MiddlewareDispatcher->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#31 /var/www/releases/20210812135306/public/typo3/sysext/backend/Classes/Http/Application.php(72): TYPO3\CMS\Core\Http\AbstractApplication->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#32 /var/www/releases/20210812135306/public/typo3/sysext/core/Classes/Http/AbstractApplication.php(97): TYPO3\CMS\Backend\Http\Application->handle(Object(TYPO3\CMS\Core\Http\ServerRequest))
#33 /var/www/releases/20210812135306/public/typo3/index.php(25): TYPO3\CMS\Core\Http\AbstractApplication->run()
#34 /var/www/releases/20210812135306/public/typo3/index.php(26): {closure}()
#35 {main}
```

**Used versions (please complete the following information):**
 - TYPO3 Version: 10.4.19
 - Browser: Chrome, but independent of browser
 - EXT:solr Version: 11.0.4
 - Used Apache Solr Version: 8.8.1
 - PHP Version: 7.4.22
 - MySQL Version: MariaDB 10.3.29

**Additional context**
It could be something that our custom extensions and/or site package does to the page record or database table definition, but since I'm only seeing sysexts `backend` and `core` and this extension in the stacktrace, I'm assuming it may be a general problem.

The error does not occur when a new page is created via the new page form, e.g. via the newPageWizard.

**Comment by dkd-kaehm** [comment]
@YetiCGN 
Thanks for reporting.
Unfortunately I can't reproduce that issue. 
The `$pageRecord` var in following method is never `null` 

https://github.com/TYPO3-Solr/ext-solr/blob/03080d4d55eeb9d50b15348f445d23e57e34e461/Classes/AbstractDataHandlerListener.php#L164-L177

Please make sure a third party EXTs hooks are properly implemented without changing the value of Call-by-Reference vars.

Take a look at #2836 as an example of possible troubles.

**Comment by YetiCGN** [comment]
I have further debugged this issue to an empty `substNEWwithIDs` array. Now as to what is causing this, I have not found the root issue yet.

**Comment by vertexvaar** [comment]
I could reproduce this issue, also because of an empty `substNEWwithIDs` array. The root cause is, that the page could not be created. I get an error for the INSERT SQL statement issued by the DataHandler.
```Field 'tx_in2comments_admin' doesn't have a default value```

You can reproduce this by creating a DB field without a default value in the `pages` table.

EXT:solr does not do any sanity check here and simply expects the value to be set which ultimately results in the mentioned exception, which will cover up the root error and therefor makes further debugging very hard.

Sorry, but the statement "The `$pageRecord` var in following method is never `null`" is wrong. You should return early if `$tceMain->substNEWwithIDs[$recordUid]` is not set
https://github.com/TYPO3-Solr/ext-solr/blob/03080d4d55eeb9d50b15348f445d23e57e34e461/Classes/IndexQueue/RecordMonitor.php#L297-L303

**Comment by einpraegsam** [comment]
Same issue on a different project. Also with MySQL strict mode. I will search for fields without default value.
