### ISSUE TITLE
[BUG] 12.0.0-beta-1; Index Queue - module broken with Typo3 12.4.3 and 12.4.4

### ISSUE THREAD

**Issue by christophs78** [TYPO3-Solr/ext-solr#3730]
**Describe the bug**
When jumping into Index Queue - module with Typo3 12.4.3 and ext-solr 12.0.0-beta-1 a exception is thrown.

This is caused by following Typo3 - Core - Commit: https://github.com/TYPO3/typo3/commit/ae08304025e756f6bcc368884f5d33e16df77fb9#diff-15620534e70cf5472fd5ad8739ed0220d78620ef98816c5f6cf51dd11b6fc653
![image](https://github.com/TYPO3-Solr/ext-solr/assets/10461942/4ddf109d-9559-410b-850e-1135129a2909)

When i manually rollback this in SelectCheckBoxElement.php it´s up an working again.

Maybe it´s to some degree kind of a fault of Typo3 and only partially related to ext-solr.

**Screenshots**
![image](https://github.com/TYPO3-Solr/ext-solr/assets/10461942/ea13bbe1-8388-41fe-8909-4e0ad9c8ccdd)

**Used versions (please complete the following information):**
 - TYPO3 Version: 12.4.3
 - EXT:solr Version: 12.0.0-beta-1
 - Used Apache Solr Version:  9.2.1
 - PHP Version: 8.1

**Additional context**
Wed, 19 Jul 2023 10:05:19 +0000 [CRITICAL] request="daab001119ec1" component="TYPO3.CMS.Core.Error.DebugExceptionHandler": Core: Exception handler (WEB: BE): TYPO3\CMS\Core\Error\Exception, code #1476107295, file /var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php, line 138: PHP Warning: Undefined array key "label" in /var/www/html/vendor/typo3/cms-backend/Classes/Form/Element/AbstractFormElement.php line 146- Exception: PHP Warning: Undefined array key "label" in /var/www/html/vendor/typo3/cms-backend/Classes/Form/Element/AbstractFormElement.php line 146, in file /var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php:138 - {"mode":"WEB","application_mode":"BE","exception_class":"TYPO3\\CMS\\Core\\Error\\Exception","exception_code":1476107295,"file":"/var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php","line":138,"message":"PHP Warning: Undefined array key \"label\" in /var/www/html/vendor/typo3/cms-backend/Classes/Form/Element/AbstractFormElement.php line 146","request_url":"http://gartenlandooe.ddev.site.res01.ads.ooe.local/typo3/module/searchbackend/index-queue?token=--AnonymizedToken--","exception":"TYPO3\\CMS\\Core\\Error\\Exception: PHP Warning: Undefined array key \"label\" in /var/www/html/vendor/typo3/cms-backend/Classes/Form/Element/AbstractFormElement.php line 146 in /var/www/html/vendor/typo3/cms-core/Classes/Error/ErrorHandler.php:138\nStack trace:\n#0 /var/www/html/vendor/typo3/cms-backend/Classes/Form/Element/AbstractFormElement.php(146): TYPO3\\CMS\\Core\\Error\\ErrorHandler->handleError(2, 'Undefined array...', '/var/www/html/v...', 146)\n#1 /var/www/html/vendor/typo3/cms-backend/Classes/Form/Element/SelectCheckBoxElement.php(271): TYPO3\\CMS\\Backend\\Form\\Element\\AbstractFormElement->wrapWithFieldsetAndLegend('<div class=\"for...')\n#2 /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/Backend/IndexingConfigurationSelectorField.php(207): TYPO3\\CMS\\Backend\\Form\\Element\\SelectCheckBoxElement->render()\n#3 /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/Backend/IndexingConfigurationSelectorField.php(109): ApacheSolrForTypo3\\Solr\\Backend\\IndexingConfigurationSelectorField->renderSelectCheckbox(Array, Array)\n#4 /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/Controller/Backend/Search/IndexQueueModuleController.php(92): ApacheSolrForTypo3\\Solr\\Backend\\IndexingConfigurationSelectorField->render()\n#5 /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/Controller/Backend/Search/IndexQueueModuleController.php(60): ApacheSolrForTypo3\\Solr\\Controller\\Backend\\Search\\IndexQueueModuleController->getIndexQueueInitializationSelector()\n#6 /var/www/html/vendor/typo3/cms-extbase/Classes/Mvc/Controller/ActionController.php(481): ApacheSolrForTypo3\\Solr\\Controller\\Backend\\Search\\IndexQueueModuleController->indexAction()\n#7 /var/www/html/vendor/typo3/cms-extbase/Classes/Mvc/Controller/ActionController.php(398): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->callActionMethod(Object(TYPO3\\CMS\\Extbase\\Mvc\\Request))\n#8 /var/www/html/vendor/typo3/cms-extbase/Classes/Mvc/Dispatcher.php(68): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->processRequest(Object(TYPO3\\CMS\\Extbase\\Mvc\\Request))\n#9 /var/www/html/vendor/typo3/cms-extbase/Classes/Core/Bootstrap.php(231): TYPO3\\CMS\\Extbase\\Mvc\\Dispatcher->dispatch(Object(TYPO3\\CMS\\Extbase\\Mvc\\Request))\n#10 /var/www/html/vendor/typo3/cms-backend/Classes/Http/RouteDispatcher.php(77): TYPO3\\CMS\\Extbase\\Core\\Bootstrap->handleBackendRequest(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#11 /var/www/html/vendor/typo3/cms-backend/Classes/Http/RequestHandler.php(104): TYPO3\\CMS\\Backend\\Http\\RouteDispatcher->dispatch(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#12 /var/www/html/vendor/typo3/cms-core/Classes/Middleware/ResponsePropagation.php(34): TYPO3\\CMS\\Backend\\Http\\RequestHandler->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#13 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\ResponsePropagation->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(TYPO3\\CMS\\Backend\\Http\\RequestHandler))\n#14 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/SiteResolver.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#15 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\SiteResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#16 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/SudoModeInterceptor.php(52): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#17 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\SudoModeInterceptor->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#18 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/AdditionalResponseHeaders.php(37): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#19 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\AdditionalResponseHeaders->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#20 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/ContentSecurityPolicyHeaders.php(52): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#21 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\ContentSecurityPolicyHeaders->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#22 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/OutputCompression.php(43): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#23 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\OutputCompression->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#24 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/BackendModuleValidator.php(152): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#25 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\BackendModuleValidator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#26 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/BackendUserAuthenticator.php(159): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#27 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\BackendUserAuthenticator->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#28 /var/www/html/vendor/typo3/cms-reactions/Classes/Http/Middleware/ReactionResolver.php(58): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#29 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Reactions\\Http\\Middleware\\ReactionResolver->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#30 /var/www/html/vendor/typo3/cms-core/Classes/Middleware/RequestTokenMiddleware.php(71): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#31 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\RequestTokenMiddleware->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#32 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/BackendRouteInitialization.php(81): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#33 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\BackendRouteInitialization->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#34 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/ContentSecurityPolicyReporter.php(41): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#35 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\ContentSecurityPolicyReporter->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#36 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/ForcedHttpsBackendRedirector.php(56): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#37 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\ForcedHttpsBackendRedirector->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#38 /var/www/html/vendor/typo3/cms-backend/Classes/Middleware/LockedBackendGuard.php(71): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#39 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Backend\\Middleware\\LockedBackendGuard->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#40 /var/www/html/vendor/typo3/cms-core/Classes/Middleware/NormalizedParamsAttribute.php(41): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#41 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#42 /var/www/html/vendor/typo3/cms-core/Classes/Middleware/VerifyHostHeader.php(55): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#43 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(162): TYPO3\\CMS\\Core\\Middleware\\VerifyHostHeader->process(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest), Object(Psr\\Http\\Server\\RequestHandlerInterface@anonymous))\n#44 /var/www/html/vendor/typo3/cms-core/Classes/Http/MiddlewareDispatcher.php(70): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#45 /var/www/html/vendor/typo3/cms-core/Classes/Http/AbstractApplication.php(80): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#46 /var/www/html/vendor/typo3/cms-backend/Classes/Http/Application.php(58): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#47 /var/www/html/vendor/typo3/cms-core/Classes/Http/AbstractApplication.php(92): TYPO3\\CMS\\Backend\\Http\\Application->handle(Object(TYPO3\\CMS\\Core\\Http\\ServerRequest))\n#48 /var/www/html/public/typo3/index.php(20): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()\n#49 /var/www/html/public/typo3/index.php(21): {closure}()\n#50 {main}"}

**Comment by christophs78** [comment]
Looks like this issue disappeared with Typo3 12.4.5. I have to look a bit more into this later and will close the issue afterwards.

**Comment by christophs78** [comment]
Fixed via https://github.com/TYPO3/typo3/commit/146e5b57a6e8fe431497dd74e608c1207f5a0b40
