### ISSUE TITLE
core_eu error

### ISSUE THREAD

**Issue by obi12341** [TYPO3-Solr/ext-solr#384]
Hello,

it looks like the core_eu conf has some errors in it.
i am using newest 4.0 config files.
You can reproduce the error with this docker container: https://hub.docker.com/r/writl/solr-typo3/  in version 4.10.4-2

855299 [http-nio-0.0.0.0-8080-exec-6] ERROR org.apache.solr.servlet.SolrDispatchFilter  ? null:org.apache.solr.common.SolrException: SolrCore 'core_eu' is not available due to init failure: Could not load conf for core core_eu: org.apache.solr.common.SolrException: Plugin init failure for [schema.xml] fieldType "text": Plugin init failure for [schema.xml] analyzer/filter: Error instantiating class: 'org.apache.lucene.analysis.miscellaneous.WordDelimiterFilterFactory'. Schema file is /opt/solr-tomcat/solr/typo3cores/conf/basque/schema.xml
	at org.apache.solr.core.CoreContainer.getCore(CoreContainer.java:745)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:299)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:207)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1096)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:674)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.solr.common.SolrException: Could not load conf for core core_eu: org.apache.solr.common.SolrException: Plugin init failure for [schema.xml] fieldType "text": Plugin init failure for [schema.xml] analyzer/filter: Error instantiating class: 'org.apache.lucene.analysis.miscellaneous.WordDelimiterFilterFactory'. Schema file is /opt/solr-tomcat/solr/typo3cores/conf/basque/schema.xml
	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:66)
	at org.apache.solr.core.CoreContainer.create(CoreContainer.java:489)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:255)
	at org.apache.solr.core.CoreContainer$1.call(CoreContainer.java:249)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	... 1 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: org.apache.solr.common.SolrException: Plugin init failure for [schema.xml] fieldType "text": Plugin init failure for [schema.xml] analyzer/filter: Error instantiating class: 'org.apache.lucene.analysis.miscellaneous.WordDelimiterFilterFactory'. Schema file is /opt/solr-tomcat/solr/typo3cores/conf/basque/schema.xml
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2263)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4000)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4789)
	at org.apache.solr.core.ConfigSetService$SchemaCaching.createIndexSchema(ConfigSetService.java:194)
	at org.apache.solr.core.ConfigSetService.getConfig(ConfigSetService.java:62)
	... 7 more
Caused by: org.apache.solr.common.SolrException: Plugin init failure for [schema.xml] fieldType "text": Plugin init failure for [schema.xml] analyzer/filter: Error instantiating class: 'org.apache.lucene.analysis.miscellaneous.WordDelimiterFilterFactory'. Schema file is /opt/solr-tomcat/solr/typo3cores/conf/basque/schema.xml
	at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:595)
	at org.apache.solr.schema.IndexSchema.<init>(IndexSchema.java:166)
	at org.apache.solr.schema.IndexSchemaFactory.create(IndexSchemaFactory.java:55)
	at org.apache.solr.schema.IndexSchemaFactory.buildIndexSchema(IndexSchemaFactory.java:69)
	at org.apache.solr.core.ConfigSetService$SchemaCaching$1.call(ConfigSetService.java:198)
	at org.apache.solr.core.ConfigSetService$SchemaCaching$1.call(ConfigSetService.java:194)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4792)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3599)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2379)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2342)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2257)
	... 11 more
Caused by: org.apache.solr.common.SolrException: Plugin init failure for [schema.xml] fieldType "text": Plugin init failure for [schema.xml] analyzer/filter: Error instantiating class: 'org.apache.lucene.analysis.miscellaneous.WordDelimiterFilterFactory'
	at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:177)
	at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:486)
	... 21 more
Caused by: org.apache.solr.common.SolrException: Plugin init failure for [schema.xml] analyzer/filter: Error instantiating class: 'org.apache.lucene.analysis.miscellaneous.WordDelimiterFilterFactory'
	at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:177)
	at org.apache.solr.schema.FieldTypePluginLoader.readAnalyzer(FieldTypePluginLoader.java:400)
	at org.apache.solr.schema.FieldTypePluginLoader.create(FieldTypePluginLoader.java:95)
	at org.apache.solr.schema.FieldTypePluginLoader.create(FieldTypePluginLoader.java:43)
	at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:151)
	... 22 more
Caused by: org.apache.solr.common.SolrException: Error instantiating class: 'org.apache.lucene.analysis.miscellaneous.WordDelimiterFilterFactory'
	at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:606)
	at org.apache.solr.schema.FieldTypePluginLoader$3.create(FieldTypePluginLoader.java:382)
	at org.apache.solr.schema.FieldTypePluginLoader$3.create(FieldTypePluginLoader.java:376)
	at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:151)
	... 26 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at org.apache.solr.core.SolrResourceLoader.newInstance(SolrResourceLoader.java:603)
	... 29 more
Caused by: java.lang.IllegalArgumentException: Unknown parameters: {rotected=basque/protwords.txt}
	at org.apache.lucene.analysis.miscellaneous.WordDelimiterFilterFactory.<init>(WordDelimiterFilterFactory.java:99)
	... 33 more

**Comment by obi12341** [comment]
See PR #385

**Comment by timoschmidt** [comment]
Thx for the pr, i'll also merge it to master
