### ISSUE TITLE
[BUG] Indexing fails with SOLR_* cObj in TypoScript

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Solr/ext-solr#4221]
**Describe the bug**
I am using the default indexing configuration for news and run manial indexing in the backend module. 

I get the following error:

```
0: Error: Call to a member function getConfigArray() on null in /var/www/html/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php:718
Stack trace:
#0 /var/www/html/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(702): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->determineExceptionHandlerClassName(Array)
#1 /var/www/html/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(660): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->createExceptionHandler(Array)
#2 /var/www/html/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(601): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->render(Object(ApacheSolrForTypo3\Solr\ContentObject\Relation), Array)
#3 /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/IndexQueue/AbstractIndexer.php(168): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle('SOLR_RELATION', Array)
#4 /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/IndexQueue/AbstractIndexer.php(91): ApacheSolrForTypo3\Solr\IndexQueue\AbstractIndexer->resolveFieldValue(Array, 'category_string...', Array, Object(TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController), 0)
#5 /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/IndexQueue/Indexer.php(384): ApacheSolrForTypo3\Solr\IndexQueue\AbstractIndexer->addDocumentFieldsFromTyposcript(Object(ApacheSolrForTypo3\Solr\System\Solr\Document\Document), Array, Array, Object(TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController), 0)
#6 /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/IndexQueue/Indexer.php(156): ApacheSolrForTypo3\Solr\IndexQueue\Indexer->itemToDocument(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item), 0)
#7 /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/IndexQueue/Indexer.php(124): ApacheSolrForTypo3\Solr\IndexQueue\Indexer->indexItem(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item), 0)
#8 /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/Domain/Index/IndexService.php(156): ApacheSolrForTypo3\Solr\IndexQueue\Indexer->index(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item))
#9 /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/Domain/Index/IndexService.php(101): ApacheSolrForTypo3\Solr\Domain\Index\IndexService->indexItem(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item), Object(ApacheSolrForTypo3\Solr\System\Configuration\TypoScriptConfiguration))
#10 /var/www/html/vendor/apache-solr-for-typo3/solr/Classes/Controller/Backend/Search/IndexQueueModuleController.php(286): ApacheSolrForTypo3\Solr\Domain\Index\IndexService->indexItems(1)
#11 /var/www/html/vendor/typo3/cms-extbase/Classes/Mvc/Controller/ActionController.php(470): ApacheSolrForTypo3\Solr\Controller\Backend\Search\IndexQueueModuleController->doIndexingRunAction()
```

**To Reproduce**
See above

**Expected behavior**
No error

**Screenshots**

**Used versions (please complete the following information):**
 - TYPO3 Version: [e.g. 13.4.1]
 - EXT:solr Version: [e.g. 13.0.0]
 - Used Apache Solr Version: [e.g. 9.5.0]
 - PHP Version: [e.g. 8.2.0]

**Additional context**

---

#### exact/previous Exception:

```
#0 /var/www/html/packages/ext-solr/Classes/ContentObject/Relation.php(451): TYPO3\CMS\Core\Context\LanguageAspectFactory::createFromSiteLanguage(NULL)
#1 /var/www/html/packages/ext-solr/Classes/ContentObject/Relation.php(122): ApacheSolrForTypo3\Solr\ContentObject\Relation->getFrontendOverlayService(Object(TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer))
#2 /var/www/html/packages/ext-solr/Classes/ContentObject/Relation.php(83): ApacheSolrForTypo3\Solr\ContentObject\Relation->getRelatedItems(Object(TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer))
#3 /var/www/html/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(654): ApacheSolrForTypo3\Solr\ContentObject\Relation->render(Array)
#4 /var/www/html/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(601): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->render(Object(ApacheSolrForTypo3\Solr\ContentObject\Relation), Array)
#5 /var/www/html/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(570): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle('SOLR_RELATION', Array, '20')
#6 /var/www/html/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(550): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSeparated(Array, '')
#7 /var/www/html/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectArrayContentObject.php(43): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGet(Array)
#8 /var/www/html/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(654): TYPO3\CMS\Frontend\ContentObject\ContentObjectArrayContentObject->render(Array)
#9 /var/www/html/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(601): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->render(Object(TYPO3\CMS\Frontend\ContentObject\ContentObjectArrayContentObject), Array)
#10 /var/www/html/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(1343): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle('COA', Array, '/stdWrap/.cObje...')
#11 /var/www/html/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(1161): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->stdWrap_cObject('', Array)
#12 /var/www/html/packages/ext-solr/Classes/ContentObject/Content.php(62): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->stdWrap('', Array)
#13 /var/www/html/packages/ext-solr/Classes/ContentObject/Content.php(40): ApacheSolrForTypo3\Solr\ContentObject\Content->getRawContent(Object(TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer), Array)
#14 /var/www/html/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(654): ApacheSolrForTypo3\Solr\ContentObject\Content->render(Array)
#15 /var/www/html/vendor/typo3/cms-frontend/Classes/ContentObject/ContentObjectRenderer.php(601): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->render(Object(ApacheSolrForTypo3\Solr\ContentObject\Content), Array)
#16 /var/www/html/packages/ext-solr/Classes/IndexQueue/AbstractIndexer.php(168): TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->cObjGetSingle('SOLR_CONTENT', Array)
#17 /var/www/html/packages/ext-solr/Classes/IndexQueue/AbstractIndexer.php(91): ApacheSolrForTypo3\Solr\IndexQueue\AbstractIndexer->resolveFieldValue(Array, 'content', Array, Object(TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController), 0)
#18 /var/www/html/packages/ext-solr/Classes/IndexQueue/Indexer.php(384): ApacheSolrForTypo3\Solr\IndexQueue\AbstractIndexer->addDocumentFieldsFromTyposcript(Object(ApacheSolrForTypo3\Solr\System\Solr\Document\Document), Array, Array, Object(TYPO3\CMS\Frontend\Controller\TypoScriptFrontendController), 0)
#19 /var/www/html/packages/ext-solr/Classes/IndexQueue/Indexer.php(156): ApacheSolrForTypo3\Solr\IndexQueue\Indexer->itemToDocument(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item), 0)
#20 /var/www/html/packages/ext-solr/Classes/IndexQueue/Indexer.php(124): ApacheSolrForTypo3\Solr\IndexQueue\Indexer->indexItem(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item), 0)
#21 /var/www/html/packages/ext-solr/Classes/Domain/Index/IndexService.php(156): ApacheSolrForTypo3\Solr\IndexQueue\Indexer->index(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item))
#22 /var/www/html/packages/ext-solr/Classes/Domain/Index/IndexService.php(101): ApacheSolrForTypo3\Solr\Domain\Index\IndexService->indexItem(Object(ApacheSolrForTypo3\Solr\IndexQueue\Item), Object(ApacheSolrForTypo3\Solr\System\Configuration\TypoScriptConfiguration))
#23 /var/www/html/packages/ext-solr/Classes/Controller/Backend/Search/IndexQueueModuleController.php(286): ApacheSolrForTypo3\Solr\Domain\Index\IndexService->indexItems(1)
#24 /var/www/html/vendor/typo3/cms-extbase/Classes/Mvc/Controller/ActionController.php(470): ApacheSolrForTypo3\Solr\Controller\Backend\Search\IndexQueueModuleController->doIndexingRunAction()
.....
#75 {main}
```

**Comment by linawolf** [comment]
If I comment out the SOLR_CONTENT section indexing works but I cannot search in the content anymore
